-- 1
CREATE TABLE posts (
	postId INT AUTO_INCREMENT,
	title VARCHAR(50) NOT NULL,
	content VARCHAR(200) NOT NULL,
	PRIMARY KEY (postId)
);

-- 2
ALTER TABLE posts
ADD writer VARCHAR(100) DEFAULT 'Anonymous',
ADD created_at DATETIME DEFAULT CURRENT_TIMESTAMP;

-- 3
ALTER TABLE posts
MODIFY content VARCHAR(50);

-- 4
ALTER TABLE posts
DROP COLUMN writer;

-- 5
DROP TABLE posts;

-- 6
CREATE TABLE IF NOT EXISTS posts (
	postId INT AUTO_INCREMENT,
	title VARCHAR(50) NOT NULL,
	content VARCHAR(200) NOT NULL,
	writer VARCHAR(100) DEFAULT 'Anonymous',
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (postId)
);

-- 7
DROP TABLE IF EXISTS posts;


# SHOW COLUMNS FROM posts;